### ISSUE TITLE
Operator Support Proxy

### ISSUE THREAD

**Issue by yapnel** [teiid/teiid-openshift-examples#62]
Hi,

Does the operator support proxy env variables? I have set this on the cluster wide on CRC and i can see the env variable propogated into the Deployment and POD but getting this error message and the pod failes to start.

Failed to pull image "registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5": rpc error: code = Unknown desc = error pinging docker registry registry.redhat.io: Get https://registry.redhat.io/v2/: dial tcp: lookup registry.redhat.io on 10.88.0.8:53: no such host.

Please advise.

Thanks

Nelson

**Comment by rareddy** [comment]
Is this on OpenShift 3.11? Then follow instructions here https://access.redhat.com/documentation/en-us/red_hat_integration/2019-12/html-single/data_virtualization/index#install-dv-operator

Somehow,  your OpenShift environment, it can't access ` registry.redhat.io`, this is not at Operator level but Openshift environment level IMO.

**Comment by yapnel** [comment]
It is OCP 4

**Comment by rareddy** [comment]
The operator should be visible through the OperatorHub then.  A usage article was written recently for this https://developers.redhat.com/blog/2020/01/21/first-steps-with-the-data-virtualization-operator-for-red-hat-openshift/

**Comment by yapnel** [comment]
I have been following this article and then I faced the issue stated earlier. I have ensured proxy set at cluster wide, pod and deployment but still hitting the problem, hence, my enquiry whether the operator needs proxy configuration. Else I'm clueless what else to test or even troubleshooting.

Thanks

**Comment by rareddy** [comment]
Operator does not need proxy configuration directly. However, if access to the `registry.redhat.io` needs to go through a proxy for pulling down the image needed for the Operator, then one needs to be configured. I found one article on configuring proxy in 4.x https://access.redhat.com/solutions/4095281

**Comment by yapnel** [comment]
Yes i have done the cluster wide proxy setting (https://docs.openshift.com/container-platform/4.2/networking/enable-cluster-wide-proxy.html). Therefore, the Deployment and POD were able to inherit the proxy env variables but it is still not able to connect to the registry.  

I have tried to oc debug pod/dv-operator but the debug POD is not starting too because it is failing to connect to the registry which left me unable to troubleshoot further at the linux level. Looks like there is no way to SSH onto the VM too otherwise i could try doing a curl with proxy to test :(

**Comment by yapnel** [comment]
Previously, i had the same problem with the OperatorHub not able to display the content from the registries. I had to set the proxy at the Deployment env variables and it started to work. I did the same thing with dv-operator hoping it will work but it didn't.

**Comment by rareddy** [comment]
This is beyond my knowledge on setting up proxy's at the cluster level. Not sure, maybe Red Hat support can help.
